### ISSUE TITLE
How to get IP address of the client?

### ISSUE THREAD

**Issue by digz6666** [CollectionFS/Meteor-http-methods#47]
I wrote small GET method that can be accessed from any IP address, so how can I get the IP address of the client? I tried following and it works on my local computer, not working on the deployed server.

```javascript
HTTP.methods({
    '/api/test': {
        get: function (data) {
            var ip_address = this.requestHeaders['x-forwarded-for'];
            console.log(ip_address);
            return 'Test';
        }
    }
});
```

**Comment by DevinXian** [comment]
`ip_address = this.request.headers['x-forwarded-for']`;
I am using nginx,  `ip_adress = this.connection.httpHeaders['x-real-ip']`
try it~

**Comment by digz6666** [comment]
@DevinXian Thanks for sharing your way, for me this.connection is undefined, so I've tried
ip_address = this.requestHeaders['x-real-ip'] and is empty.

**Comment by digz6666** [comment]
@DevinXian I found it:
```javascript
HTTP.methods({
    '/api/test': {
        get: function (data) {
            var ip_address = this.request.connection.remoteAddress;
            console.log(ip_address);
            return 'Test';
        }
    }
});
```
