### ISSUE TITLE
New cordova uploads

### ISSUE THREAD

**Issue by guidouil** [CollectionFS/Meteor-http-methods#49]
I'm having an issue with the coming Cordova update with Meteor 1.3 (currently beta 5) and this limitation is a locker `res.setHeader("Access-Control-Allow-Origin", "http://meteor.local");`
We spoke about it [here](https://github.com/meteor/meteor/issues/6050#issuecomment-183662319)
So it will need to be `localhost:<port>` but you'll have to figure which port the local server is currently running... 
Not to good to help but I can reproduce ^_^

**Comment by martijnwalraven** [comment]
The client will send an `Origin` header with `http://localhost:<port>`. You will have to validate this (if you only want to allow access from `localhost`) and then echo the origin as the value of `Access-Control-Allow-Origin`.

**Comment by raix** [comment]
interesting, thanks guys
